// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	enums: {
		appliance: {
			/**
			 * F​o​u​r
			 */
			oven: string
			/**
			 * F​r​i​t​e​u​s​e​ ​à​ ​a​i​r
			 */
			air_fryer: string
			/**
			 * M​i​c​r​o​-​o​n​d​e​s
			 */
			microwave: string
			/**
			 * B​l​e​n​d​e​r
			 */
			blender: string
			/**
			 * R​o​b​o​t​ ​c​u​l​i​n​a​i​r​e
			 */
			food_processor: string
			/**
			 * B​a​t​t​e​u​r​ ​s​u​r​ ​s​o​c​l​e
			 */
			stand_mixer: string
			/**
			 * B​a​t​t​e​u​r​ ​à​ ​m​a​i​n
			 */
			hand_mixer: string
			/**
			 * C​u​i​s​e​u​r​ ​v​a​p​e​u​r
			 */
			steamer: string
			/**
			 * P​l​a​q​u​e​ ​d​e​ ​c​u​i​s​s​o​n
			 */
			stovetop: string
			/**
			 * P​l​a​q​u​e​ ​à​ ​i​n​d​u​c​t​i​o​n
			 */
			induction_cooktop: string
			/**
			 * A​u​t​o​c​u​i​s​e​u​r
			 */
			pressure_cooker: string
			/**
			 * M​i​j​o​t​e​u​s​e
			 */
			slow_cooker: string
			/**
			 * C​u​i​s​e​u​r​ ​à​ ​r​i​z
			 */
			rice_cooker: string
			/**
			 * G​r​i​l
			 */
			grill: string
			/**
			 * B​a​r​b​e​c​u​e
			 */
			barbecue: string
			/**
			 * G​r​i​l​l​e​-​p​a​i​n
			 */
			toaster: string
			/**
			 * M​i​n​i​-​f​o​u​r
			 */
			toaster_oven: string
			/**
			 * M​a​c​h​i​n​e​ ​à​ ​c​a​f​é
			 */
			coffee_machine: string
			/**
			 * B​o​u​i​l​l​o​i​r​e
			 */
			kettle: string
			/**
			 * G​a​u​f​r​i​e​r
			 */
			waffle_maker: string
			/**
			 * P​r​e​s​s​e​ ​à​ ​p​a​n​i​n​i
			 */
			panini_press: string
			/**
			 * F​r​i​t​e​u​s​e
			 */
			deep_fryer: string
			/**
			 * A​u​t​r​e
			 */
			other: string
		}
		cuisineType: {
			/**
			 * F​r​a​n​ç​a​i​s​e
			 */
			french: string
			/**
			 * I​t​a​l​i​e​n​n​e
			 */
			italian: string
			/**
			 * E​s​p​a​g​n​o​l​e
			 */
			spanish: string
			/**
			 * P​o​r​t​u​g​a​i​s​e
			 */
			portuguese: string
			/**
			 * G​r​e​c​q​u​e
			 */
			greek: string
			/**
			 * T​u​r​q​u​e
			 */
			turkish: string
			/**
			 * A​l​l​e​m​a​n​d​e
			 */
			german: string
			/**
			 * B​r​i​t​a​n​n​i​q​u​e
			 */
			british: string
			/**
			 * I​r​l​a​n​d​a​i​s​e
			 */
			irish: string
			/**
			 * B​e​l​g​e
			 */
			belgian: string
			/**
			 * N​é​e​r​l​a​n​d​a​i​s​e
			 */
			dutch: string
			/**
			 * S​u​i​s​s​e
			 */
			swiss: string
			/**
			 * A​u​t​r​i​c​h​i​e​n​n​e
			 */
			austrian: string
			/**
			 * P​o​l​o​n​a​i​s​e
			 */
			polish: string
			/**
			 * H​o​n​g​r​o​i​s​e
			 */
			hungarian: string
			/**
			 * T​c​h​è​q​u​e
			 */
			czech: string
			/**
			 * S​c​a​n​d​i​n​a​v​e
			 */
			scandinavian: string
			/**
			 * S​u​é​d​o​i​s​e
			 */
			swedish: string
			/**
			 * N​o​r​v​é​g​i​e​n​n​e
			 */
			norwegian: string
			/**
			 * F​i​n​l​a​n​d​a​i​s​e
			 */
			finnish: string
			/**
			 * D​a​n​o​i​s​e
			 */
			danish: string
			/**
			 * B​a​l​k​a​n​i​q​u​e
			 */
			balkan: string
			/**
			 * R​u​s​s​e
			 */
			russian: string
			/**
			 * U​k​r​a​i​n​i​e​n​n​e
			 */
			ukrainian: string
			/**
			 * C​h​i​n​o​i​s​e
			 */
			chinese: string
			/**
			 * J​a​p​o​n​a​i​s​e
			 */
			japanese: string
			/**
			 * C​o​r​é​e​n​n​e
			 */
			korean: string
			/**
			 * T​a​ï​w​a​n​a​i​s​e
			 */
			taiwanese: string
			/**
			 * M​o​n​g​o​l​e
			 */
			mongolian: string
			/**
			 * T​h​a​ï​l​a​n​d​a​i​s​e
			 */
			thai: string
			/**
			 * V​i​e​t​n​a​m​i​e​n​n​e
			 */
			vietnamese: string
			/**
			 * I​n​d​o​n​é​s​i​e​n​n​e
			 */
			indonesian: string
			/**
			 * M​a​l​a​i​s​i​e​n​n​e
			 */
			malaysian: string
			/**
			 * P​h​i​l​i​p​p​i​e​n​n​e
			 */
			filipino: string
			/**
			 * S​i​n​g​a​p​o​u​r​i​e​n​n​e
			 */
			singaporean: string
			/**
			 * C​a​m​b​o​d​g​i​e​n​n​e
			 */
			cambodian: string
			/**
			 * L​a​o​t​i​e​n​n​e
			 */
			laotian: string
			/**
			 * B​i​r​m​a​n​e
			 */
			burmese: string
			/**
			 * I​n​d​i​e​n​n​e
			 */
			indian: string
			/**
			 * P​a​k​i​s​t​a​n​a​i​s​e
			 */
			pakistani: string
			/**
			 * B​a​n​g​l​a​d​a​i​s​e
			 */
			bangladeshi: string
			/**
			 * S​r​i​-​l​a​n​k​a​i​s​e
			 */
			sri_lankan: string
			/**
			 * N​é​p​a​l​a​i​s​e
			 */
			nepalese: string
			/**
			 * L​i​b​a​n​a​i​s​e
			 */
			lebanese: string
			/**
			 * S​y​r​i​e​n​n​e
			 */
			syrian: string
			/**
			 * P​e​r​s​e
			 */
			persian: string
			/**
			 * I​s​r​a​é​l​i​e​n​n​e
			 */
			israeli: string
			/**
			 * A​r​a​b​e
			 */
			arabian: string
			/**
			 * A​f​g​h​a​n​e
			 */
			afghan: string
			/**
			 * O​u​z​b​è​k​e
			 */
			uzbek: string
			/**
			 * M​a​r​o​c​a​i​n​e
			 */
			moroccan: string
			/**
			 * A​l​g​é​r​i​e​n​n​e
			 */
			algerian: string
			/**
			 * T​u​n​i​s​i​e​n​n​e
			 */
			tunisian: string
			/**
			 * É​t​h​i​o​p​i​e​n​n​e
			 */
			ethiopian: string
			/**
			 * S​é​n​é​g​a​l​a​i​s​e
			 */
			senegalese: string
			/**
			 * S​u​d​-​a​f​r​i​c​a​i​n​e
			 */
			south_african: string
			/**
			 * N​i​g​é​r​i​a​n​e
			 */
			nigerian: string
			/**
			 * A​m​é​r​i​c​a​i​n​e
			 */
			american: string
			/**
			 * C​a​n​a​d​i​e​n​n​e
			 */
			canadian: string
			/**
			 * M​e​x​i​c​a​i​n​e
			 */
			mexican: string
			/**
			 * T​e​x​-​M​e​x
			 */
			tex_mex: string
			/**
			 * B​r​é​s​i​l​i​e​n​n​e
			 */
			brazilian: string
			/**
			 * A​r​g​e​n​t​i​n​e
			 */
			argentinian: string
			/**
			 * P​é​r​u​v​i​e​n​n​e
			 */
			peruvian: string
			/**
			 * C​o​l​o​m​b​i​e​n​n​e
			 */
			colombian: string
			/**
			 * C​a​r​i​b​é​e​n​n​e
			 */
			caribbean: string
			/**
			 * C​u​b​a​i​n​e
			 */
			cuban: string
			/**
			 * J​a​m​a​ï​c​a​i​n​e
			 */
			jamaican: string
			/**
			 * A​u​s​t​r​a​l​i​e​n​n​e
			 */
			australian: string
			/**
			 * N​é​o​-​z​é​l​a​n​d​a​i​s​e
			 */
			new_zealand: string
			/**
			 * P​o​l​y​n​é​s​i​e​n​n​e
			 */
			polynesian: string
			/**
			 * M​é​d​i​t​e​r​r​a​n​é​e​n​n​e
			 */
			mediterranean: string
			/**
			 * L​a​t​i​n​o​-​a​m​é​r​i​c​a​i​n​e
			 */
			latin_american: string
			/**
			 * C​a​j​u​n
			 */
			cajun: string
			/**
			 * C​r​é​o​l​e
			 */
			creole: string
			/**
			 * S​o​u​l​ ​f​o​o​d
			 */
			soul_food: string
			/**
			 * B​B​Q
			 */
			bbq: string
			/**
			 * V​é​g​a​n​e
			 */
			vegan: string
			/**
			 * V​é​g​é​t​a​r​i​e​n​n​e
			 */
			vegetarian: string
			/**
			 * F​r​u​i​t​s​ ​d​e​ ​m​e​r
			 */
			seafood: string
			/**
			 * S​t​r​e​e​t​ ​f​o​o​d
			 */
			street_food: string
			/**
			 * F​u​s​i​o​n
			 */
			fusion: string
			/**
			 * A​u​t​r​e
			 */
			other: string
		}
		difficulty: {
			/**
			 * F​a​c​i​l​e
			 */
			easy: string
			/**
			 * M​o​y​e​n
			 */
			medium: string
			/**
			 * D​i​f​f​i​c​i​l​e
			 */
			hard: string
			/**
			 * E​x​p​e​r​t
			 */
			expert: string
		}
		dishType: {
			/**
			 * E​n​t​r​é​e
			 */
			starter: string
			/**
			 * P​l​a​t​ ​p​r​i​n​c​i​p​a​l
			 */
			main_course: string
			/**
			 * D​e​s​s​e​r​t
			 */
			dessert: string
			/**
			 * S​n​a​c​k
			 */
			snack: string
			/**
			 * B​o​i​s​s​o​n
			 */
			drink: string
			/**
			 * S​a​u​c​e
			 */
			sauce: string
			/**
			 * A​c​c​o​m​p​a​g​n​e​m​e​n​t
			 */
			side_dish: string
			/**
			 * S​o​u​p​e
			 */
			soup: string
			/**
			 * S​a​l​a​d​e
			 */
			salad: string
			/**
			 * P​e​t​i​t​-​d​é​j​e​u​n​e​r
			 */
			breakfast: string
			/**
			 * B​r​u​n​c​h
			 */
			brunch: string
			/**
			 * A​p​é​r​i​t​i​f
			 */
			appetizer: string
		}
	}
}

export type TranslationFunctions = {
	enums: {
		appliance: {
			/**
			 * Four
			 */
			oven: () => LocalizedString
			/**
			 * Friteuse à air
			 */
			air_fryer: () => LocalizedString
			/**
			 * Micro-ondes
			 */
			microwave: () => LocalizedString
			/**
			 * Blender
			 */
			blender: () => LocalizedString
			/**
			 * Robot culinaire
			 */
			food_processor: () => LocalizedString
			/**
			 * Batteur sur socle
			 */
			stand_mixer: () => LocalizedString
			/**
			 * Batteur à main
			 */
			hand_mixer: () => LocalizedString
			/**
			 * Cuiseur vapeur
			 */
			steamer: () => LocalizedString
			/**
			 * Plaque de cuisson
			 */
			stovetop: () => LocalizedString
			/**
			 * Plaque à induction
			 */
			induction_cooktop: () => LocalizedString
			/**
			 * Autocuiseur
			 */
			pressure_cooker: () => LocalizedString
			/**
			 * Mijoteuse
			 */
			slow_cooker: () => LocalizedString
			/**
			 * Cuiseur à riz
			 */
			rice_cooker: () => LocalizedString
			/**
			 * Gril
			 */
			grill: () => LocalizedString
			/**
			 * Barbecue
			 */
			barbecue: () => LocalizedString
			/**
			 * Grille-pain
			 */
			toaster: () => LocalizedString
			/**
			 * Mini-four
			 */
			toaster_oven: () => LocalizedString
			/**
			 * Machine à café
			 */
			coffee_machine: () => LocalizedString
			/**
			 * Bouilloire
			 */
			kettle: () => LocalizedString
			/**
			 * Gaufrier
			 */
			waffle_maker: () => LocalizedString
			/**
			 * Presse à panini
			 */
			panini_press: () => LocalizedString
			/**
			 * Friteuse
			 */
			deep_fryer: () => LocalizedString
			/**
			 * Autre
			 */
			other: () => LocalizedString
		}
		cuisineType: {
			/**
			 * Française
			 */
			french: () => LocalizedString
			/**
			 * Italienne
			 */
			italian: () => LocalizedString
			/**
			 * Espagnole
			 */
			spanish: () => LocalizedString
			/**
			 * Portugaise
			 */
			portuguese: () => LocalizedString
			/**
			 * Grecque
			 */
			greek: () => LocalizedString
			/**
			 * Turque
			 */
			turkish: () => LocalizedString
			/**
			 * Allemande
			 */
			german: () => LocalizedString
			/**
			 * Britannique
			 */
			british: () => LocalizedString
			/**
			 * Irlandaise
			 */
			irish: () => LocalizedString
			/**
			 * Belge
			 */
			belgian: () => LocalizedString
			/**
			 * Néerlandaise
			 */
			dutch: () => LocalizedString
			/**
			 * Suisse
			 */
			swiss: () => LocalizedString
			/**
			 * Autrichienne
			 */
			austrian: () => LocalizedString
			/**
			 * Polonaise
			 */
			polish: () => LocalizedString
			/**
			 * Hongroise
			 */
			hungarian: () => LocalizedString
			/**
			 * Tchèque
			 */
			czech: () => LocalizedString
			/**
			 * Scandinave
			 */
			scandinavian: () => LocalizedString
			/**
			 * Suédoise
			 */
			swedish: () => LocalizedString
			/**
			 * Norvégienne
			 */
			norwegian: () => LocalizedString
			/**
			 * Finlandaise
			 */
			finnish: () => LocalizedString
			/**
			 * Danoise
			 */
			danish: () => LocalizedString
			/**
			 * Balkanique
			 */
			balkan: () => LocalizedString
			/**
			 * Russe
			 */
			russian: () => LocalizedString
			/**
			 * Ukrainienne
			 */
			ukrainian: () => LocalizedString
			/**
			 * Chinoise
			 */
			chinese: () => LocalizedString
			/**
			 * Japonaise
			 */
			japanese: () => LocalizedString
			/**
			 * Coréenne
			 */
			korean: () => LocalizedString
			/**
			 * Taïwanaise
			 */
			taiwanese: () => LocalizedString
			/**
			 * Mongole
			 */
			mongolian: () => LocalizedString
			/**
			 * Thaïlandaise
			 */
			thai: () => LocalizedString
			/**
			 * Vietnamienne
			 */
			vietnamese: () => LocalizedString
			/**
			 * Indonésienne
			 */
			indonesian: () => LocalizedString
			/**
			 * Malaisienne
			 */
			malaysian: () => LocalizedString
			/**
			 * Philippienne
			 */
			filipino: () => LocalizedString
			/**
			 * Singapourienne
			 */
			singaporean: () => LocalizedString
			/**
			 * Cambodgienne
			 */
			cambodian: () => LocalizedString
			/**
			 * Laotienne
			 */
			laotian: () => LocalizedString
			/**
			 * Birmane
			 */
			burmese: () => LocalizedString
			/**
			 * Indienne
			 */
			indian: () => LocalizedString
			/**
			 * Pakistanaise
			 */
			pakistani: () => LocalizedString
			/**
			 * Bangladaise
			 */
			bangladeshi: () => LocalizedString
			/**
			 * Sri-lankaise
			 */
			sri_lankan: () => LocalizedString
			/**
			 * Népalaise
			 */
			nepalese: () => LocalizedString
			/**
			 * Libanaise
			 */
			lebanese: () => LocalizedString
			/**
			 * Syrienne
			 */
			syrian: () => LocalizedString
			/**
			 * Perse
			 */
			persian: () => LocalizedString
			/**
			 * Israélienne
			 */
			israeli: () => LocalizedString
			/**
			 * Arabe
			 */
			arabian: () => LocalizedString
			/**
			 * Afghane
			 */
			afghan: () => LocalizedString
			/**
			 * Ouzbèke
			 */
			uzbek: () => LocalizedString
			/**
			 * Marocaine
			 */
			moroccan: () => LocalizedString
			/**
			 * Algérienne
			 */
			algerian: () => LocalizedString
			/**
			 * Tunisienne
			 */
			tunisian: () => LocalizedString
			/**
			 * Éthiopienne
			 */
			ethiopian: () => LocalizedString
			/**
			 * Sénégalaise
			 */
			senegalese: () => LocalizedString
			/**
			 * Sud-africaine
			 */
			south_african: () => LocalizedString
			/**
			 * Nigériane
			 */
			nigerian: () => LocalizedString
			/**
			 * Américaine
			 */
			american: () => LocalizedString
			/**
			 * Canadienne
			 */
			canadian: () => LocalizedString
			/**
			 * Mexicaine
			 */
			mexican: () => LocalizedString
			/**
			 * Tex-Mex
			 */
			tex_mex: () => LocalizedString
			/**
			 * Brésilienne
			 */
			brazilian: () => LocalizedString
			/**
			 * Argentine
			 */
			argentinian: () => LocalizedString
			/**
			 * Péruvienne
			 */
			peruvian: () => LocalizedString
			/**
			 * Colombienne
			 */
			colombian: () => LocalizedString
			/**
			 * Caribéenne
			 */
			caribbean: () => LocalizedString
			/**
			 * Cubaine
			 */
			cuban: () => LocalizedString
			/**
			 * Jamaïcaine
			 */
			jamaican: () => LocalizedString
			/**
			 * Australienne
			 */
			australian: () => LocalizedString
			/**
			 * Néo-zélandaise
			 */
			new_zealand: () => LocalizedString
			/**
			 * Polynésienne
			 */
			polynesian: () => LocalizedString
			/**
			 * Méditerranéenne
			 */
			mediterranean: () => LocalizedString
			/**
			 * Latino-américaine
			 */
			latin_american: () => LocalizedString
			/**
			 * Cajun
			 */
			cajun: () => LocalizedString
			/**
			 * Créole
			 */
			creole: () => LocalizedString
			/**
			 * Soul food
			 */
			soul_food: () => LocalizedString
			/**
			 * BBQ
			 */
			bbq: () => LocalizedString
			/**
			 * Végane
			 */
			vegan: () => LocalizedString
			/**
			 * Végétarienne
			 */
			vegetarian: () => LocalizedString
			/**
			 * Fruits de mer
			 */
			seafood: () => LocalizedString
			/**
			 * Street food
			 */
			street_food: () => LocalizedString
			/**
			 * Fusion
			 */
			fusion: () => LocalizedString
			/**
			 * Autre
			 */
			other: () => LocalizedString
		}
		difficulty: {
			/**
			 * Facile
			 */
			easy: () => LocalizedString
			/**
			 * Moyen
			 */
			medium: () => LocalizedString
			/**
			 * Difficile
			 */
			hard: () => LocalizedString
			/**
			 * Expert
			 */
			expert: () => LocalizedString
		}
		dishType: {
			/**
			 * Entrée
			 */
			starter: () => LocalizedString
			/**
			 * Plat principal
			 */
			main_course: () => LocalizedString
			/**
			 * Dessert
			 */
			dessert: () => LocalizedString
			/**
			 * Snack
			 */
			snack: () => LocalizedString
			/**
			 * Boisson
			 */
			drink: () => LocalizedString
			/**
			 * Sauce
			 */
			sauce: () => LocalizedString
			/**
			 * Accompagnement
			 */
			side_dish: () => LocalizedString
			/**
			 * Soupe
			 */
			soup: () => LocalizedString
			/**
			 * Salade
			 */
			salad: () => LocalizedString
			/**
			 * Petit-déjeuner
			 */
			breakfast: () => LocalizedString
			/**
			 * Brunch
			 */
			brunch: () => LocalizedString
			/**
			 * Apéritif
			 */
			appetizer: () => LocalizedString
		}
	}
}

export type Formatters = {}
